language: csharp
solution: TravisCI.sln
install:
  - nuget restore TravisCI.sln
  - nuget install NUnit.ConsoleRunner -Version 3.9.0 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release TravisCI.sln
  - mono ./testrunner/NUnit.ConsoleRunner.3.9.0/tools/nunit3-console.exe ./NUnitTest/bin/Release/NUnitTest.dll
notifications:
    email: false
    slack: traviscitest:gUIyWdfEWDjc7x88yDTu6aqZ
        on_success: always