language: csharp
solution: TravisCI.sln
before_install:
  - sudo apt-get install nunit-console
before_script:
  - nuget restore TravisCI.sln
after_script:
- nunit-console Tests/bin/Release/Tests.dll
  notifications:
    slack: traviscitest:gUIyWdfEWDjc7x88yDTu6aqZ
    on_success: always