language: csharp
solution: TravisCI.sln
install:
  - nuget restore solution-name.sln
  - nuget install NUnit.Runners -Version 3.11.0 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release TravisCI.sln
  - mono ./testrunner/NUnit.Runners.3.11.0/tools/nunit-console.exe ./MyProject.Tests/bin/Release/MyProject.Tests.dll
notifications:
    slack: traviscitest:gUIyWdfEWDjc7x88yDTu6aqZ
    on_success: always